import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class", // Enable dark mode with a class
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./node_modules/flowbite/**/*.js",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: "#fff7ed",
                    100: "#ffedd5",
                    200: "#fed7aa",
                    300: "#fdba74",
                    400: "#fb923c",
                    500: "#f97316",
                    600: "#ea580c",
                    700: "#c2410c",
                    800: "#9a3412",
                    900: "#7c2d12",
                    950: "#431407",
                },
                neutral: {
                    // Renamed 'netral' to 'neutral' for consistency
                    50: "#FFFFFF",
                    100: "#EEF1F4",
                    200: "#EAEBF0",
                    300: "#D0D2DD",
                    400: "#A9ACB8",
                    500: "#6D6F77",
                    600: "#272727",
                },
                success: {
                    50: "#F2FBE4",
                    100: "#E4F7C4",
                    200: "#D7F4A9",
                    300: "#C9EF8A",
                    400: "#BCEC6F",
                    500: "#AEE851",
                },
                danger: {
                    50: "#FFE3E0",
                    100: "#FFC7C2",
                    200: "#FFA69E",
                    300: "#FF8A80",
                    400: "#FF6E61",
                    500: "#FF5242",
                },
                warning: {
                    50: "#FDFBB8",
                    100: "#FCF996",
                    200: "#FBF77B",
                    300: "#FAF659",
                    400: "#F9F43D",
                    500: "#F8F21B",
                },
                info: {
                    50: "#DFF2FE",
                    100: "#BCE5FE",
                    200: "#A0D9FE",
                    300: "#7ECCFD",
                    400: "#62C1FD",
                    500: "#3FB3FC",
                },
            },
            fontFamily: {
                body: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],
                sans: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],
            },
        },
    },
    plugins: [require("flowbite/plugin")],
};
